# Generated by Django 2.0.6 on 2019-07-31 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'ordering': ['-created'], 'verbose_name': 'О нас', 'verbose_name_plural': 'О магазине'},
        ),
        migrations.AlterModelOptions(
            name='contacts',
            options={'ordering': ['-created'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
