# Generated by Django 2.0.6 on 2019-08-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20190731_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_one', models.EmailField(blank=True, max_length=100, verbose_name='Email-1')),
                ('email_two', models.EmailField(blank=True, max_length=100, verbose_name='Email-2')),
                ('website', models.URLField(blank=True, max_length=150, verbose_name='Сайт')),
                ('phone_one', models.CharField(blank=True, max_length=100, verbose_name='Телефон-1')),
                ('phone_two', models.CharField(blank=True, max_length=100, verbose_name='Телефон-2')),
                ('address', models.CharField(blank=True, max_length=150, verbose_name='Адрес')),
                ('is_active', models.BooleanField(default=True, verbose_name='Модерация')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name_plural': 'Контакты',
                'verbose_name': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Backcall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=100, verbose_name='Телефон')),
                ('text', models.TextField(blank=True, max_length=1000, verbose_name='Сообщение')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name_plural': 'Обратный звонок',
                'verbose_name': 'Обратный звонок',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Модерация')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name_plural': 'Политика',
                'verbose_name': 'Политика',
            },
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Модерация')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name_plural': 'Политика',
                'verbose_name': 'Политика',
            },
        ),
    ]
