# Generated by Django 2.0.6 on 2019-08-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_address_backcall_delivery_privacypolicy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ['-created'], 'verbose_name': 'Доставка', 'verbose_name_plural': 'Доставка'},
        ),
        migrations.AddField(
            model_name='address',
            name='title',
            field=models.CharField(blank=True, max_length=150, verbose_name='Заголовок'),
        ),
    ]
