# Generated by Django 2.0.6 on 2019-12-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_headerwidgetinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerwidgetinfo',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Модерация'),
        ),
    ]
