# Generated by Django 2.0.6 on 2019-06-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20190530_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_two',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Доп. email'),
        ),
    ]
