# Generated by Django 2.0.6 on 2019-06-14 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_email_two'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_two',
        ),
    ]
