# Generated by Django 2.0.6 on 2019-06-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190121_0716'),
        ('profiles', '0006_auto_20190614_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='products',
            field=models.ManyToManyField(to='shop.Product', verbose_name='Продукты'),
        ),
    ]
