# Generated by Django 2.0.6 on 2019-08-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletteruser',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
    ]
