# Generated by Django 2.0.6 on 2019-08-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='status',
            field=models.IntegerField(choices=[(1, 'Черновик'), (2, 'Опубликовано')], verbose_name='Статус'),
        ),
    ]
