# Generated by Django 2.0.6 on 2019-08-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_auto_20190821_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='email',
            new_name='users_email',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='file',
            field=models.FileField(blank=True, upload_to='newsletter_files/%Y/%m/%d', verbose_name='Файл'),
        ),
    ]
