# Generated by Django 2.0.6 on 2019-09-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0006_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletteruser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Модерация'),
        ),
    ]
