# Generated by Django 2.0.6 on 2019-09-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_category_attributes'),
        ('newsletter', '0007_newsletteruser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='prod_tpl', to='shop.Product', verbose_name='Товары'),
        ),
    ]
