# Generated by Django 2.0.6 on 2018-07-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Катагория')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='Транслит')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_activ', models.BooleanField(default=True, verbose_name='Модерация')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
    ]
