# Generated by Django 2.0.6 on 2018-12-26 14:30

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Атрибут')),
                ('is_active', models.BooleanField(default=True, verbose_name='Модерация')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Отредактирован')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.Attribute', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name_plural': 'Атрибуты товара',
                'verbose_name': 'Атрибут',
            },
        ),
        migrations.CreateModel(
            name='Bestseller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Модерация')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
            ],
            options={
                'verbose_name_plural': 'Блок Бестселлеры',
                'verbose_name': 'Бестселлер',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, unique=True, verbose_name='Бренд')),
                ('slug', models.SlugField(max_length=200, verbose_name='Транслит')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='img_brand/%y/%m/%d/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Модерация')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Отредактирован')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Бренды',
                'verbose_name': 'Бренд',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Катагория')),
                ('slug', models.SlugField(max_length=250, verbose_name='Транслит')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('img', models.ImageField(blank=True, upload_to='img_category/%y/%m/%d/', verbose_name='Изображение категории')),
                ('is_active', models.BooleanField(default=True, verbose_name='Модерация')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Отредактирован')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.Category', verbose_name='Родительская категория')),
            ],
            options={
                'ordering': ('tree_id', 'level'),
                'verbose_name_plural': 'Категории',
                'verbose_name': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='CategoryIndexPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Модерация')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.CategoryIndexPage', verbose_name='Родительская категория')),
                ('sortcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Category', verbose_name='Вывод категорий на главной странице')),
            ],
            options={
                'verbose_name_plural': 'Вывод из категорий на главной',
                'verbose_name': 'Вывод из категории на главной',
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Модерация')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Отредактирован')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Attribute', verbose_name='Атрибут')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='Название товара')),
                ('slug', models.SlugField(verbose_name='Транслит')),
                ('meta_keywords', models.CharField(blank=True, max_length=250, verbose_name='Клюевые слова')),
                ('meta_descriptions', models.CharField(blank=True, max_length=250, verbose_name='Мета описание')),
                ('descriptions', models.TextField(blank=True, verbose_name='Описание')),
                ('descriptions_two', models.TextField(blank=True, verbose_name='Доп.описание')),
                ('images', models.ImageField(blank=True, upload_to='img_product/%y/%m/%d/', verbose_name='Изображение товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('discount', models.IntegerField(default=0, verbose_name='Скидка')),
                ('new', models.BooleanField(default=False, verbose_name='Новый товар')),
                ('akciya', models.BooleanField(default=False, verbose_name='Акция')),
                ('akciya_text', models.TextField(blank=True, verbose_name='Описание')),
                ('timer', models.BooleanField(default=False, verbose_name='Таймер')),
                ('timer_before', models.DateTimeField(blank=True, null=True, verbose_name='Дата таймера')),
                ('stock', models.PositiveIntegerField(verbose_name='Количество')),
                ('vendor_code', models.IntegerField(default=0, verbose_name='Артикул товара')),
                ('is_active', models.BooleanField(default=True, verbose_name='Модерация')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Отредактирован')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Brand', verbose_name='Бренд')),
                ('category', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Category', verbose_name='Категория')),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name_plural': 'Товары',
                'verbose_name': 'Товар',
            },
        ),
        migrations.CreateModel(
            name='ProductAlbomImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('image', models.ImageField(blank=True, upload_to='product-albom-images/%y/%m/%d/', verbose_name='Загрузить картинку')),
                ('is_active', models.BooleanField(default=True, verbose_name='Модерация')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Отредактирован')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.ProductAlbomImages', verbose_name='Родительская категория')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='shop.Product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name_plural': 'Фото товаров',
                'verbose_name': 'Фото товара',
            },
        ),
        migrations.CreateModel(
            name='SaleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Модерация')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.SaleCategory', verbose_name='Родительская категория')),
                ('sale_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Category', verbose_name='Выберите категорию')),
            ],
            options={
                'verbose_name_plural': 'Распродажи по категориям',
                'verbose_name': 'Распродажа по категориям',
            },
        ),
        migrations.CreateModel(
            name='SaleProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Модерация')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.SaleProduct', verbose_name='Родительская категория')),
                ('sale_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product', verbose_name='Выберите товар')),
            ],
            options={
                'verbose_name_plural': 'Распродажи по товарам',
                'verbose_name': 'Распродажа по товарам',
            },
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=250, verbose_name='Значение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Модерация')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Отредактирован')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Attribute', verbose_name='Атрибут')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.Value', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name_plural': 'Значения',
                'verbose_name': 'Значение',
            },
        ),
        migrations.AddField(
            model_name='entry',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product', verbose_name='Продукт'),
        ),
        migrations.AddField(
            model_name='entry',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Value', verbose_name='Значение'),
        ),
        migrations.AddField(
            model_name='bestseller',
            name='bestseller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Category', verbose_name='Выберите категорию'),
        ),
        migrations.AddField(
            model_name='bestseller',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.Bestseller', verbose_name='Родительская категория'),
        ),
    ]
