# Generated by Django 2.0.6 on 2018-08-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(blank=True, upload_to='img_category/%y/%m/%d/', verbose_name='Изображение категории'),
        ),
    ]
