# Generated by Django 2.0.6 on 2018-09-25 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productalbomimages',
            name='image',
            field=models.ImageField(blank=True, upload_to='product-albom-images/%y/%m/%d/', verbose_name='Фото товара'),
        ),
        migrations.AlterField(
            model_name='productalbomimages',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='shop.Product', verbose_name='Продукт'),
        ),
    ]
