# Generated by Django 2.0.6 on 2019-01-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='descriptions_two',
            field=models.TextField(blank=True, editable=False, verbose_name='Доп.описание'),
        ),
    ]
