# Generated by Django 2.0.6 on 2018-09-25 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20180925_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Attribute', verbose_name='Атрибут'),
        ),
    ]
