# Generated by Django 2.0.6 on 2018-09-03 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAlbomImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Название')),
                ('image', models.ImageField(blank=True, upload_to='product-albom-images/%y/%m/%d/', verbose_name='Фото товара')),
                ('is_activ', models.BooleanField(default=True, verbose_name='Модерация')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Отредактирован')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='shop.Product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name_plural': 'Фото товаров',
                'verbose_name': 'Фото товара',
            },
        ),
    ]
