# Generated by Django 2.0.6 on 2018-09-25 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20180925_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productalbomimages',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='shop.Product', verbose_name='Продукт'),
        ),
    ]
