# Generated by Django 2.0.6 on 2018-07-30 11:16

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(blank=True, upload_to=shop.models.image_folder, verbose_name='Изображение товара'),
        ),
    ]
