# Generated by Django 2.0.6 on 2019-07-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_categoryindexpage_brands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryindexpage',
            name='brands',
            field=models.ManyToManyField(blank=True, to='shop.Brand', verbose_name='Сортировать по брендам'),
        ),
    ]
