# Generated by Django 2.0.6 on 2018-10-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20180925_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='akciya',
            field=models.BooleanField(default=False, verbose_name='Акция'),
        ),
        migrations.AddField(
            model_name='product',
            name='new',
            field=models.BooleanField(default=False, verbose_name='Новый товар'),
        ),
        migrations.AddField(
            model_name='product',
            name='timer',
            field=models.BooleanField(default=False, verbose_name='Таймер'),
        ),
        migrations.AddField(
            model_name='product',
            name='timer_before',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата таймера'),
        ),
    ]
