# Generated by Django 2.0.6 on 2018-09-15 07:27

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20180915_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_activ',
            field=models.BooleanField(default=True, verbose_name='Модерация'),
        ),
        migrations.AlterField(
            model_name='value',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Attribute', verbose_name='Атрибут'),
        ),
        migrations.AlterField(
            model_name='value',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.Value', verbose_name='Родительская категория'),
        ),
    ]
