# Generated by Django 2.0.6 on 2019-09-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190722_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='attributes',
            field=models.ManyToManyField(blank=True, to='shop.Attribute', verbose_name='Атрибуты товара'),
        ),
    ]
