# Generated by Django 2.0.6 on 2018-10-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20181010_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='akciya_text',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
