# Generated by Django 2.0.6 on 2018-11-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_akciya_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productalbomimages',
            name='image',
            field=models.ImageField(blank=True, upload_to='product-albom-images/%y/%m/%d/', verbose_name='Загрузить картинку'),
        ),
    ]
