# Generated by Django 2.0.6 on 2019-09-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20190918_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='is_filter',
            field=models.BooleanField(default=False, verbose_name='Фильтр'),
        ),
    ]
