# Generated by Django 2.0.6 on 2018-11-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20181127_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='meta_descriptions',
            field=models.CharField(blank=True, max_length=250, verbose_name='Мета описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=250, verbose_name='Клюевые слова'),
        ),
    ]
