# Generated by Django 2.0.6 on 2018-11-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20181127_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor_code',
            field=models.IntegerField(default=0, verbose_name='Артикул товара'),
        ),
    ]
