# Generated by Django 2.0.6 on 2019-12-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_pricelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Валюта')),
                ('sign', models.CharField(max_length=20, verbose_name='Знак')),
                ('abbreviation', models.CharField(max_length=20, verbose_name='Сокращение')),
                ('course', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Курс')),
                ('is_default', models.BooleanField(default=True, verbose_name='Основная валюта')),
                ('is_active', models.BooleanField(default=False, verbose_name='Модерация')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name_plural': 'Валюты',
                'verbose_name': 'Валюта',
            },
        ),
    ]
