# Generated by Django 2.0.6 on 2019-12-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_pricelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='id_cml',
            field=models.UUIDField(blank=True, null=True, verbose_name='Выгрузка'),
        ),
        migrations.AddField(
            model_name='brand',
            name='id_cml',
            field=models.UUIDField(blank=True, null=True, verbose_name='Выгрузка'),
        ),
        migrations.AddField(
            model_name='category',
            name='id_cml',
            field=models.UUIDField(blank=True, null=True, verbose_name='Выгрузка'),
        ),
        migrations.AddField(
            model_name='product',
            name='id_cml',
            field=models.UUIDField(blank=True, null=True, verbose_name='Выгрузка'),
        ),
        migrations.AddField(
            model_name='productalbomimages',
            name='id_cml',
            field=models.UUIDField(blank=True, null=True, verbose_name='Выгрузка'),
        ),
        migrations.AddField(
            model_name='value',
            name='id_cml',
            field=models.UUIDField(blank=True, null=True, verbose_name='Выгрузка'),
        ),
    ]
