# Generated by Django 2.0.6 on 2018-12-12 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20181207_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bestseller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Модерация')),
                ('bestseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Category', verbose_name='Выберите категорию')),
            ],
            options={
                'verbose_name_plural': 'Блок Бестселлеры',
                'verbose_name': 'Бестселлер',
            },
        ),
    ]
