# Generated by Django 2.0.6 on 2020-01-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20200113_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryindexpage',
            name='sort',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Позиция блока'),
        ),
    ]
