# Generated by Django 2.0.6 on 2018-12-14 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_bestseller'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Модерация')),
                ('sale_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Category', verbose_name='Выберите категорию')),
            ],
            options={
                'verbose_name_plural': 'Распродажи по категориям',
                'verbose_name': 'Распродажа по категориям',
            },
        ),
    ]
