# Generated by Django 2.0.6 on 2018-12-14 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_salecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Модерация')),
                ('sale_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product', verbose_name='Выберите товар')),
            ],
            options={
                'verbose_name': 'Распродажа по товарам',
                'verbose_name_plural': 'Распродажи по товарам',
            },
        ),
    ]
