# Generated by Django 2.0.6 on 2020-02-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_categoryindexpage_sort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vendor_code',
            field=models.CharField(blank=True, default=0, max_length=100, null=True, verbose_name='Артикул'),
        ),
    ]
