# Generated by Django 2.0.6 on 2020-02-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20200213_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vendor_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Артикул'),
        ),
    ]
