# Generated by Django 2.0.6 on 2018-12-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название баннера')),
                ('description', models.TextField(blank=True, verbose_name='Описание баннера')),
                ('images', models.ImageField(upload_to='img_banners/%y/%m/%d/', verbose_name='Изображение баннера')),
                ('is_active', models.BooleanField(default=False, verbose_name='Модерация')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Отредактирован')),
            ],
            options={
                'verbose_name_plural': 'Баннеры',
                'verbose_name': 'Баннер',
            },
        ),
    ]
