# Generated by Django 2.0.6 on 2018-12-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='link',
            field=models.URLField(blank=True, max_length=250, verbose_name='Ссылка'),
        ),
    ]
