# Generated by Django 2.0.6 on 2019-01-08 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('info', '0002_banners_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=200, verbose_name='Транслит')),
                ('metakeywords', models.CharField(blank=True, max_length=200, verbose_name='Ключевые слова')),
                ('metadescription', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('text', models.TextField(verbose_name='Статья')),
                ('images', models.ImageField(blank=True, upload_to='news/%y/%m/%d/', verbose_name='Изображение статьи')),
                ('video', models.URLField(blank=True, verbose_name='Ссылка на видео')),
                ('count', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('is_active', models.BooleanField(default=False, verbose_name='Модерация')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Новости',
                'ordering': ['-created'],
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
