# Generated by Django 2.0.6 on 2019-03-06 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('info', '0003_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('email', models.EmailField(blank=True, max_length=50, verbose_name='e-mail')),
                ('user_name', models.CharField(blank=True, max_length=100, verbose_name='Логин пользователя')),
                ('like', models.IntegerField(default=0, verbose_name='like')),
                ('dislike', models.IntegerField(default=0, verbose_name='dislike')),
                ('count_comment', models.IntegerField(default=0, verbose_name='Количество комментариев')),
                ('is_active', models.BooleanField(default=False, verbose_name='Модерация')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('object_id', models.PositiveIntegerField()),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='info.Comment', verbose_name='Родительская категория')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('user_dislike', models.ManyToManyField(blank=True, related_name='users_dislike', to=settings.AUTH_USER_MODEL, verbose_name='Кто поставил дизлайк')),
                ('user_like', models.ManyToManyField(blank=True, related_name='users_like', to=settings.AUTH_USER_MODEL, verbose_name='Кто поставил лайк')),
            ],
            options={
                'verbose_name_plural': 'Коментарии',
                'ordering': ['-created'],
                'verbose_name': 'Комментарий',
            },
        ),
    ]
