# Generated by Django 2.0.6 on 2019-02-01 10:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('info', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_like',
            field=models.ManyToManyField(blank=True, related_name='users_like', to=settings.AUTH_USER_MODEL, verbose_name='Кто поставил лайк'),
        ),
    ]
