# Generated by Django 2.0.6 on 2019-03-13 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user_dislike',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user_like',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
