# Generated by Django 2.0.6 on 2019-03-28 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0002_auto_20190121_0716'),
        ('info', '0005_auto_20190313_0818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=250, verbose_name='Посетитель')),
                ('city', models.CharField(blank=True, max_length=200, verbose_name='Ваш город')),
                ('image', models.ImageField(blank=True, upload_to='review/%y/%m/%d/', verbose_name='Изображение')),
                ('merits', models.TextField(blank=True, verbose_name='Достоинства')),
                ('limitations', models.TextField(blank=True, verbose_name='Недостатки')),
                ('comment', models.TextField(blank=True, verbose_name='Текст отзыва')),
                ('email', models.EmailField(blank=True, max_length=50, verbose_name='e-mail')),
                ('video', models.URLField(blank=True, max_length=500, verbose_name='Ссылка на видео')),
                ('rating', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Рейтинг')),
                ('period', models.IntegerField(blank=True, choices=[(0, 'Меньше месяца'), (1, '1 Месяц'), (2, '3 Месяца'), (3, '6 Месяцев'), (4, '1 Год'), (5, 'Больше года')], verbose_name='Период использования')),
                ('is_active', models.BooleanField(default=False, verbose_name='Модерация')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.Product', verbose_name='Товар')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('user_dislike', models.ManyToManyField(blank=True, related_name='review_users_dislike', to=settings.AUTH_USER_MODEL, verbose_name='Кто поставил дизлайк')),
                ('user_like', models.ManyToManyField(blank=True, related_name='review_users_like', to=settings.AUTH_USER_MODEL, verbose_name='Кто поставил лайк')),
            ],
            options={
                'verbose_name_plural': 'Отзывы',
                'verbose_name': 'Отзыв',
                'ordering': ['-created'],
            },
        ),
    ]
