# Generated by Django 2.0.6 on 2018-12-26 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Всего')),
                ('full_name', models.CharField(default='', max_length=250, verbose_name='Фио')),
                ('phone', models.CharField(max_length=25, verbose_name='Телефон')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='Адрес')),
                ('buying_type', models.CharField(choices=[('take_out', 'Самовывоз'), ('delivery', 'Доставка')], default='take_out', max_length=100, verbose_name='Тип заказа')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Дата доставки')),
                ('comment', models.TextField(verbose_name='Комментарий к заказу')),
                ('status', models.IntegerField(choices=[(0, 'На регистрации'), (1, 'На исполнении'), (2, 'Исполнен')], default=0, verbose_name='Статус заказа')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Cart', verbose_name='Корзина')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Заказы',
                'verbose_name': 'Заказ',
            },
        ),
    ]
