# Generated by Django 2.0.6 on 2018-11-02 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20181024_0954'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='comments',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cart.Cart', verbose_name='Корзина'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='buying_type',
            field=models.IntegerField(choices=[(0, 'Самовывоз'), (1, 'Доставка')], verbose_name='Тип заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'На регистрации'), (1, 'На исполнении'), (2, 'Исполнен')], default=0, verbose_name='Статус заказа'),
        ),
    ]
