# Generated by Django 2.0.6 on 2018-11-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20181102_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buying_type',
            field=models.IntegerField(choices=[(0, 'Самовывоз'), (1, 'Доставка')], default=1, verbose_name='Тип заказа'),
        ),
    ]
