# Generated by Django 2.0.6 on 2018-11-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(default='', max_length=250, verbose_name='Фио'),
        ),
        migrations.AlterField(
            model_name='order',
            name='buying_type',
            field=models.IntegerField(choices=[(0, 'Самовывоз'), (1, 'Доставка')], verbose_name='Тип заказа'),
        ),
    ]
